<!-- 
Codes Generated By VForm:
https://www.vform666.com
-->

<template>
    <el-form :model="formData" ref="vForm" :rules="rules" label-position="left" label-width="80px"
      size="default" @submit.prevent>
      <div class="static-content-item">
        <div>固定表格表单</div>
      </div>
      <div class="static-content-item">
        <el-divider direction="horizontal"></el-divider>
      </div>
      <div class="table-container">
        <table class="table-layout">
          <tbody>
            <tr>
              <td class="table-cell">
                <div class="static-content-item">
                  <div>姓名</div>
                </div>
              </td>
              <td class="table-cell">
                <el-form-item label="" label-width="0" prop="input69467" class="small-margin-bottom">
                  <el-input v-model="formData.input69467" type="text" clearable></el-input>
                </el-form-item>
              </td>
              <td class="table-cell">
                <div class="static-content-item">
                  <div>性别</div>
                </div>
              </td>
              <td class="table-cell">
                <el-form-item label="" label-width="0" prop="input94101" class="small-margin-bottom">
                  <el-input v-model="formData.input94101" type="text" clearable></el-input>
                </el-form-item>
              </td>
              <td class="table-cell">
                <div class="static-content-item">
                  <div>出生年月</div>
                </div>
              </td>
              <td class="table-cell">
                <el-form-item label="" label-width="0" prop="input33884" class="small-margin-bottom">
                  <el-input v-model="formData.input33884" type="text" clearable></el-input>
                </el-form-item>
              </td>
              <td class="table-cell">
                <div class="static-content-item">
                  <div>民族</div>
                </div>
              </td>
              <td class="table-cell">
                <el-form-item label="" label-width="0" prop="input39759" class="small-margin-bottom">
                  <el-input v-model="formData.input39759" type="text" clearable></el-input>
                </el-form-item>
              </td>
            </tr>
            <tr>
              <td class="table-cell">
                <div class="static-content-item">
                  <div>政治面貌</div>
                </div>
              </td>
              <td class="table-cell">
                <el-form-item label="" label-width="0" prop="input25562" class="small-margin-bottom">
                  <el-input v-model="formData.input25562" type="text" clearable></el-input>
                </el-form-item>
              </td>
              <td class="table-cell">
                <div class="static-content-item">
                  <div>学历</div>
                </div>
              </td>
              <td class="table-cell">
                <el-form-item label="" label-width="0" prop="input20620" class="small-margin-bottom">
                  <el-input v-model="formData.input20620" type="text" clearable></el-input>
                </el-form-item>
              </td>
              <td class="table-cell">
                <div class="static-content-item">
                  <div>职称</div>
                </div>
              </td>
              <td class="table-cell">
                <el-form-item label="" label-width="0" prop="input116146" class="small-margin-bottom">
                  <el-input v-model="formData.input116146" type="text" clearable></el-input>
                </el-form-item>
              </td>
              <td class="table-cell">
                <div class="static-content-item">
                  <div>联系电话</div>
                </div>
              </td>
              <td class="table-cell">
                <el-form-item label="" label-width="0" prop="input26162" class="small-margin-bottom">
                  <el-input v-model="formData.input26162" type="text" clearable></el-input>
                </el-form-item>
              </td>
            </tr>
            <tr>
              <td class="table-cell">
                <div class="static-content-item">
                  <div>职务</div>
                </div>
              </td>
              <td class="table-cell" colspan="3">
                <el-form-item label="" label-width="0" prop="input109798" class="small-margin-bottom">
                  <el-input v-model="formData.input109798" type="text" clearable></el-input>
                </el-form-item>
              </td>
              <td class="table-cell" rowspan="3">
                <div class="static-content-item">
                  <div v-html="免<br>冠<br>照"></div>
                </div>
              </td>
              <td class="table-cell" colspan="3" rowspan="3">
                <el-form-item label="" label-width="0" prop="pictureupload93431" class="small-margin-bottom">
                  <el-upload :file-list="pictureupload93431FileList" :headers="pictureupload93431UploadHeaders"
                    :data="pictureupload93431UploadData" list-type="picture-card" show-file-list :limit="1">
                    <template #default><i class="el-icon-plus"></i></template></el-upload>
                </el-form-item>
              </td>
            </tr>
            <tr>
              <td class="table-cell">
                <div class="static-content-item">
                  <div>籍贯</div>
                </div>
              </td>
              <td class="table-cell" colspan="3">
                <el-form-item label="" label-width="0" prop="input94664" class="small-margin-bottom">
                  <el-input v-model="formData.input94664" type="text" clearable></el-input>
                </el-form-item>
              </td>
            </tr>
            <tr>
              <td class="table-cell">
                <div class="static-content-item">
                  <div>联系地址</div>
                </div>
              </td>
              <td class="table-cell" colspan="3">
                <el-form-item label="" label-width="0" prop="input67241" class="small-margin-bottom">
                  <el-input v-model="formData.input67241" type="text" clearable></el-input>
                </el-form-item>
              </td>
            </tr>
            <tr>
              <td class="table-cell">
                <div class="static-content-item">
                  <div>参加工作时间</div>
                </div>
              </td>
              <td class="table-cell" colspan="3">
                <el-form-item label="" label-width="0" prop="input15786" class="small-margin-bottom">
                  <el-input v-model="formData.input15786" type="text" clearable></el-input>
                </el-form-item>
              </td>
              <td class="table-cell">
                <div class="static-content-item">
                  <div>身份证号码</div>
                </div>
              </td>
              <td class="table-cell" colspan="3">
                <el-form-item label="" label-width="0" prop="input102875" class="small-margin-bottom">
                  <el-input v-model="formData.input102875" type="text" clearable></el-input>
                </el-form-item>
              </td>
            </tr>
            <tr>
              <td class="table-cell" rowspan="4">
                <div class="static-content-item">
                  <div v-html="工<br>作<br>经<br>历"></div>
                </div>
              </td>
              <td class="table-cell" colspan="2">
                <div class="static-content-item">
                  <div>工作起止时间</div>
                </div>
              </td>
              <td class="table-cell" colspan="3">
                <div class="static-content-item">
                  <div>单位名称</div>
                </div>
              </td>
              <td class="table-cell">
                <div class="static-content-item">
                  <div>部门</div>
                </div>
              </td>
              <td class="table-cell">
                <div class="static-content-item">
                  <div>职务</div>
                </div>
              </td>
            </tr>
            <tr>
              <td class="table-cell" colspan="2">
                <el-form-item label="" label-width="0" prop="input36015" class="small-margin-bottom">
                  <el-input v-model="formData.input36015" type="text" clearable></el-input>
                </el-form-item>
              </td>
              <td class="table-cell" colspan="3">
                <el-form-item label="" label-width="0" prop="input100474" class="small-margin-bottom">
                  <el-input v-model="formData.input100474" type="text" clearable></el-input>
                </el-form-item>
              </td>
              <td class="table-cell">
                <el-form-item label="" label-width="0" prop="input38749" class="small-margin-bottom">
                  <el-input v-model="formData.input38749" type="text" clearable></el-input>
                </el-form-item>
              </td>
              <td class="table-cell">
                <el-form-item label="" label-width="0" prop="input11767" class="small-margin-bottom">
                  <el-input v-model="formData.input11767" type="text" clearable></el-input>
                </el-form-item>
              </td>
            </tr>
            <tr>
              <td class="table-cell" colspan="2">
                <el-form-item label="" label-width="0" prop="input23991" class="small-margin-bottom">
                  <el-input v-model="formData.input23991" type="text" clearable></el-input>
                </el-form-item>
              </td>
              <td class="table-cell" colspan="3">
                <el-form-item label="" label-width="0" prop="input45589" class="small-margin-bottom">
                  <el-input v-model="formData.input45589" type="text" clearable></el-input>
                </el-form-item>
              </td>
              <td class="table-cell">
                <el-form-item label="" label-width="0" prop="input103953" class="small-margin-bottom">
                  <el-input v-model="formData.input103953" type="text" clearable></el-input>
                </el-form-item>
              </td>
              <td class="table-cell">
                <el-form-item label="" label-width="0" prop="input100153" class="small-margin-bottom">
                  <el-input v-model="formData.input100153" type="text" clearable></el-input>
                </el-form-item>
              </td>
            </tr>
            <tr>
              <td class="table-cell" colspan="2">
                <el-form-item label="" label-width="0" prop="input89113" class="small-margin-bottom">
                  <el-input v-model="formData.input89113" type="text" clearable></el-input>
                </el-form-item>
              </td>
              <td class="table-cell" colspan="3">
                <el-form-item label="" label-width="0" prop="input81121" class="small-margin-bottom">
                  <el-input v-model="formData.input81121" type="text" clearable></el-input>
                </el-form-item>
              </td>
              <td class="table-cell">
                <el-form-item label="" label-width="0" prop="input87205" class="small-margin-bottom">
                  <el-input v-model="formData.input87205" type="text" clearable></el-input>
                </el-form-item>
              </td>
              <td class="table-cell">
                <el-form-item label="" label-width="0" prop="input11679" class="small-margin-bottom">
                  <el-input v-model="formData.input11679" type="text" clearable></el-input>
                </el-form-item>
              </td>
            </tr>
            <tr>
              <td class="table-cell" rowspan="5">
                <div class="static-content-item">
                  <div v-html="教<br>育<br>经<br>历"></div>
                </div>
              </td>
              <td class="table-cell" colspan="2">
                <div class="static-content-item">
                  <div>就读起止时间</div>
                </div>
              </td>
              <td class="table-cell" colspan="3">
                <div class="static-content-item">
                  <div>学校名称</div>
                </div>
              </td>
              <td class="table-cell">
                <div class="static-content-item">
                  <div>专业</div>
                </div>
              </td>
              <td class="table-cell">
                <div class="static-content-item">
                  <div>个人嘉奖</div>
                </div>
              </td>
            </tr>
            <tr>
              <td class="table-cell" colspan="2">
                <el-form-item label="" label-width="0" prop="input23131" class="small-margin-bottom">
                  <el-input v-model="formData.input23131" type="text" clearable></el-input>
                </el-form-item>
              </td>
              <td class="table-cell" colspan="3">
                <el-form-item label="" label-width="0" prop="input48471" class="small-margin-bottom">
                  <el-input v-model="formData.input48471" type="text" clearable></el-input>
                </el-form-item>
              </td>
              <td class="table-cell">
                <el-form-item label="" label-width="0" prop="input36467" class="small-margin-bottom">
                  <el-input v-model="formData.input36467" type="text" clearable></el-input>
                </el-form-item>
              </td>
              <td class="table-cell">
                <el-form-item label="" label-width="0" prop="input94195" class="small-margin-bottom">
                  <el-input v-model="formData.input94195" type="text" clearable></el-input>
                </el-form-item>
              </td>
            </tr>
            <tr>
              <td class="table-cell" colspan="2">
                <el-form-item label="" label-width="0" prop="input58024" class="small-margin-bottom">
                  <el-input v-model="formData.input58024" type="text" clearable></el-input>
                </el-form-item>
              </td>
              <td class="table-cell" colspan="3">
                <el-form-item label="" label-width="0" prop="input49755" class="small-margin-bottom">
                  <el-input v-model="formData.input49755" type="text" clearable></el-input>
                </el-form-item>
              </td>
              <td class="table-cell">
                <el-form-item label="" label-width="0" prop="input37508" class="small-margin-bottom">
                  <el-input v-model="formData.input37508" type="text" clearable></el-input>
                </el-form-item>
              </td>
              <td class="table-cell">
                <el-form-item label="" label-width="0" prop="input119621" class="small-margin-bottom">
                  <el-input v-model="formData.input119621" type="text" clearable></el-input>
                </el-form-item>
              </td>
            </tr>
            <tr>
              <td class="table-cell" colspan="2">
                <el-form-item label="" label-width="0" prop="input18533" class="small-margin-bottom">
                  <el-input v-model="formData.input18533" type="text" clearable></el-input>
                </el-form-item>
              </td>
              <td class="table-cell" colspan="3">
                <el-form-item label="" label-width="0" prop="input113730" class="small-margin-bottom">
                  <el-input v-model="formData.input113730" type="text" clearable></el-input>
                </el-form-item>
              </td>
              <td class="table-cell">
                <el-form-item label="" label-width="0" prop="input61815" class="small-margin-bottom">
                  <el-input v-model="formData.input61815" type="text" clearable></el-input>
                </el-form-item>
              </td>
              <td class="table-cell">
                <el-form-item label="" label-width="0" prop="input60413" class="small-margin-bottom">
                  <el-input v-model="formData.input60413" type="text" clearable></el-input>
                </el-form-item>
              </td>
            </tr>
            <tr>
              <td class="table-cell" colspan="2">
                <el-form-item label="" label-width="0" prop="input20952" class="small-margin-bottom">
                  <el-input v-model="formData.input20952" type="text" clearable></el-input>
                </el-form-item>
              </td>
              <td class="table-cell" colspan="3">
                <el-form-item label="" label-width="0" prop="input21146" class="small-margin-bottom">
                  <el-input v-model="formData.input21146" type="text" clearable></el-input>
                </el-form-item>
              </td>
              <td class="table-cell">
                <el-form-item label="" label-width="0" prop="input62312" class="small-margin-bottom">
                  <el-input v-model="formData.input62312" type="text" clearable></el-input>
                </el-form-item>
              </td>
              <td class="table-cell">
                <el-form-item label="" label-width="0" prop="input49056" class="small-margin-bottom">
                  <el-input v-model="formData.input49056" type="text" clearable></el-input>
                </el-form-item>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </el-form>
    
  </template>
  
  <script>
    import {
      defineComponent,
      toRefs,
      reactive,
      getCurrentInstance
    }
    from 'vue'
    export default defineComponent({
      components: {},
      props: {},
      setup() {
        const state = reactive({
          formData: {
            input69467: "",
            input94101: "",
            input33884: "",
            input39759: "",
            input25562: "",
            input20620: "",
            input116146: "",
            input26162: "",
            input109798: "",
            pictureupload93431: null,
            input94664: "",
            input67241: "",
            input15786: "",
            input102875: "",
            input36015: "",
            input100474: "",
            input38749: "",
            input11767: "",
            input23991: "",
            input45589: "",
            input103953: "",
            input100153: "",
            input89113: "",
            input81121: "",
            input87205: "",
            input11679: "",
            input23131: "",
            input48471: "",
            input36467: "",
            input94195: "",
            input58024: "",
            input49755: "",
            input37508: "",
            input119621: "",
            input18533: "",
            input113730: "",
            input61815: "",
            input60413: "",
            input20952: "",
            input21146: "",
            input62312: "",
            input49056: "",
          },
          rules: {},
          pictureupload93431FileList: [],
          pictureupload93431UploadHeaders: {},
          pictureupload93431UploadData: {},
        })
        const instance = getCurrentInstance()
        const submitForm = () => {
          instance.proxy.$refs['vForm'].validate(valid => {
            if (!valid) return
            //TODO: 提交表单
          })
        }
        const resetForm = () => {
          instance.proxy.$refs['vForm'].resetFields()
        }
        return {
          ...toRefs(state),
          submitForm,
          resetForm
        }
      }
    })
    
  </script>
  
  <style lang="scss">
    .el-input-number.full-width-input,
    .el-cascader.full-width-input {
      width: 100% !important;
    }
    
    .el-form-item--medium {
      .el-radio {
        line-height: 36px !important;
      }
      
      .el-rate {
        margin-top: 8px;
      }
    }
    
    .el-form-item--small {
      .el-radio {
        line-height: 32px !important;
      }
      
      .el-rate {
        margin-top: 6px;
      }
    }
    
    .el-form-item--mini {
      .el-radio {
        line-height: 28px !important;
      }
      
      .el-rate {
        margin-top: 4px;
      }
    }
    
    .clear-fix:before,
    .clear-fix:after {
      display: table;
      content: "";
    }
    
    .clear-fix:after {
      clear: both;
    }
    
    .float-right {
      float: right;
    }
    
    .small-margin-bottom.el-form-item {
      margin-bottom: 3px;
    }
    
  </style>
  
  <style lang="scss" scoped>
    div.table-container {
      table.table-layout {
        width: 100%;
        table-layout: fixed;
        border-collapse: collapse;
  
        td.table-cell {
          display: table-cell;
          height: 36px;
          border: 1px solid #e1e2e3;
        }
      }
    }
    
    div.tab-container {}
    
    .label-left-align :deep(.el-form-item__label) {
      text-align: left;
    }
    
    .label-center-align :deep(.el-form-item__label) {
      text-align: center;
    }
    
    .label-right-align :deep(.el-form-item__label) {
      text-align: right;
    }
    
    .custom-label {}
    
    .static-content-item {
      min-height: 20px;
      display: flex;
      align-items: center;
  
      :deep(.el-divider--horizontal) {
        margin: 0;
      }
    }
    
  </style>